# Author - Hritwik Agarwal <hritwik72@gmail.com>
# Date - 20 July 2023
# Description - buildspec.yml is used to build artifact in aws codebuild service
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  
    commands:
      - echo Build initialized on `date`
      - cd ./test-function
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo "Zipping deployment package..."
      - ls -lart
      - zip -r9 ./Test-Function.zip ./node_modules
      - zip -u Test-Function.zip index.js package.json package-lock.json route.json
  post_build:
    commands:
      - ls -lart
      - aws lambda update-function-code --function-name Test-Function --zip-file fileb://Test-Function.zip
      - echo Build completed on `date`





